test main branch checkout

diff --git a/.github/workflows/v2dl3-vegas.yml b/.github/workflows/v2dl3-vegas.yml
--- a/.github/workflows/v2dl3-vegas.yml
+++ b/.github/workflows/v2dl3-vegas.yml
@@ -36,37 +36,45 @@ jobs:
       - uses: actions/checkout@v3
 
       #- name: flake8
+      - name: Checkout main branch
+        uses: actions/checkout@v3
+          with:
+            ref: main
+        run:
+          ls ./
+          cat utils/v2dl3-vegas.yml
 
       # Runs a single command using the runners shell
-      - name: Pull docker image
-        run: |
-          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
-          docker pull $DOCKER_IMAGE
+      # - name: Pull docker image
+      #   run: |
+      #     docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
+      #     docker pull $DOCKER_IMAGE
 
-      - name: Install new branch and generate .fits outputs
-        run: |
-          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
-          cd V2DL3 \
-          && bash utils/vegas_docker_test_runs.sh OUTDIR=$NEW_DIR \
-          "
+      # - name: Install new branch and generate .fits outputs
+      #   run: |
+      #     docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
+      #     cd V2DL3 \
+      #     && bash utils/vegas_docker_test_runs.sh OUTDIR=$NEW_DIR \
+      #     "
 
-      - name: Install main branch and generate control outputs
-        if: success() || failure()
-        run: |
-          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
-          cd V2DL3 \
-          && git config --global --add safe.directory /V2DL3 \
-          && git checkout -t origin/main \
-          && pip install . \
-          && bash utils/vegas_docker_test_runs.sh OUTDIR=$CONTROL_DIR
-          "
+      # - name: Install main branch and generate control outputs
 
-      - name: Install fitsdiff
-        run: |
-          sudo apt-get install -qq astropy-utils
+      #   if: success() || failure()
+      #   run: |
+      #     docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
+      #     cd V2DL3 \
+      #     && git config --global --add safe.directory /V2DL3 \
+      #     && git checkout -t origin/main \
+      #     && pip install . \
+      #     && bash utils/vegas_docker_test_runs.sh OUTDIR=$CONTROL_DIR
+      #     "
 
-      - name: Compare fits outputs
-        run: |
-          sudo chown -R 777 $NEW_DIR
-          sudo chown -R 777 $CONTROL_DIR
-          bash utils/compare_fits_dirs.sh $NEW_DIR $CONTROL_DIR
+      # - name: Install fitsdiff
+      #   run: |
+      #     sudo apt-get install -qq astropy-utils
+
+      # - name: Compare fits outputs
+      #   run: |
+      #     sudo chown -R 777 $NEW_DIR
+      #     sudo chown -R 777 $CONTROL_DIR
+      #     bash utils/compare_fits_dirs.sh $NEW_DIR $CONTROL_DIR
